# Development overrides for Docker Compose
version: '3.8'

services:
  backend:
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./backend:/var/www
      - backend_vendor:/var/www/vendor
    environment:
      - APP_ENV=local
      - APP_DEBUG=true

  frontend:
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next
    environment:
      - NODE_ENV=development

  redis:
    ports:
      - "${REDIS_PORT:-6379}:6379"

volumes:
  backend_vendor:
  frontend_node_modules:
  frontend_next: